### ISSUE TITLE
How to make Pick Up not required

### ISSUE THREAD

**Issue by mrsdesign** [WC-Local-Pickup/woocommerce-local-pickup-time#106] opened 2020-11-10 23:46 UTC
I am looking to make the pickup time NOT required on checkout - as I am now selling Gift Cards that don't require pickup.

How do I change this?

I don't have that much experience with code - any assistance would be appreciated!

**Comment by timnolte** [comment] 2021-01-23 02:47
This is a duplicate of #71

**Closed by timnolte** 2021-01-23 02:47 UTC
Labels: duplicate, enhancement
